### ISSUE TITLE
movieDetail($row['YTS'], false);

### ISSUE THREAD

**Issue by ghost** [koenhendriks/YifyAPI#5]
Hi, I love your wrapper. I gives me GREAT info on new data. The problem I have is the data I've already collected. The above line dumps the info but how do I get at the torrents?

include('YTS.php');
$ytsag = new YTS();
$new_movie = $ytsag->movieDetail($row['YTS'], false);
$T1=$new_movie->torrents[0]."<BR>";
$T1_url=$T1->url;

Just gives the error: Undefined property: stdClass::$torrents, I can see everything with a var_dump, I just can't seem to put it into variables.

**Comment by koenhendriks** [comment]
I noticed the ```movieDetail``` method returns an object with a single property ```movie```. 

I pushed an update to the wrapper, it now returns the object with movie details directly, and your code should work fine if you update the wrapper.

**Comment by ghost** [comment]
Sun of a gun, I'm not loosing my mind? LOL FANTASTIC!!! Thank you.
