### ISSUE TITLE
I wounder

### ISSUE THREAD

**Issue by ghost** [koenhendriks/YifyAPI#7]
I wounder if there is a way to skip the "Fatal error: Uncaught Exception: HTTP request failed. Error was: file_get_contents" because when YTS is under maintenance or I'm off-line, most of my system crashs with that error. Like today, YTS is under maintenance but I'd still like to proceed.

$movie_details=@$ytsag->movieDetail($YTS, false);
var_dump($movie_details);
exit;

Never gets to the var_dump and I can't see how to by pass the error.

**Comment by koenhendriks** [comment]
Well there is lots you can do but a quick example could be:

```php
try {    
    $movie_details=@$ytsag->movieDetail($YTS, false);
    var_dump($movie_details);
} catch (Exception $e) {
    echo 'YTS is under maintenance or offline.';
}
```

**Comment by ghost** [comment]
Fantastic. I can skip the checks on the YTS system then in some of the pages for example the details where I'm just checking for updated data. THANK YOU.
